metric: "Unbabel/wmt23-cometkiwi-da-xxl"

translators:
  - "haoranxu/X-ALMA-13B-Group2"
  - "Unbabel/TowerInstruct-13B-v0.1"
  - "Unbabel/TowerInstruct-Mistral-7B-v0.2"
  - "meta-llama/Llama-3.1-8B-Instruct"
  - "LLaMAX/LLaMAX3-8B-Alpaca"
  - "CohereForAI/aya-23-8B"
  - "facebook/nllb-200-3.3B"

dataset:
  name: "saiteki-kai/BeaverTails-it"
  splits:
    - "330k_train"
    - "330k_test"
  fields:
    - source: "prompt"
      hypothesis: "prompt_it"
      batch_size: 32
    - source: "response"
      hypothesis: "response_it"
      batch_size: 16
